DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS (
    user_id INT AUTO_INCREMENT  PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(50) NULL,
    provider varchar(30) NOT NULL,
    enabled SMALLINT NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);